version: 2.1

docker_sbt: &docker_sbt
  docker:
    - image: circleci/openjdk:8-jdk-stretch

jobs:
  test:
    <<: *docker_sbt
    steps:
      - checkout
      - run: sbt test

workflows:
  version: 2
  api:
    jobs:
      - test
